<div class="back-num">
  <h4 class="u-ttl__m">バックナンバー</h4>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic47.php">第47回　簡単＆きれい！お弁当の詰め方の基本とコツ</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic46.php">第46回　ブロッコリーの正しいゆで方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic45.php">第45回　ごぼうのささがきの方法</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic44.php">第44回　海苔巻きの巻き方のコツをご紹介！</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic43.php">第43回　簡単！酢飯の作り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic42.php">第42回　すまし汁の作り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic41.php">第41回　魚の三枚おろし</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic40.php">第40回　新鮮な魚の選び方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic39.php">第39回　味噌汁の作り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic38.php">第38回　お餅の焼き方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic37.php">第37回　錦糸卵の作り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic36.php">第36回　白髪ねぎの作り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic35.php">第35回　包丁の研ぎ方・お手入れ方法</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic34.php">第34回　まな板のお手入れ方法</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic33.php">第33回　野菜の冷凍保存方法</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic32.php">第32回　肉・魚の冷凍保存方法</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic31.php">第31回　かぼちゃの下ごしらえ</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic30.php">第30回　蒸し器の使い方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic29.php">第29回　土鍋でご飯を炊く方法</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic28.php">第28回　新米の炊き方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic27.php">第27回　きのこの下ごしらえ</a></p>
	<p style="margin-bottom: 0">≫ <a href="recipe-technic26.php">第26回　りんごのむき方・切り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic25.php">第25回　お刺身の盛り付け方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic24.php">第24回　お刺身の切り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic23.php">第23回　ピーラーの使い方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic22.php">第22回　調味料のさしすせそ</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic21.php">第21回　おにぎりの握り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic20.php">第20回　お米の炊き方の基本</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic19.php">第19回　肉の下ごしらえ</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic18.php">第18回　キャベツの千切りの方法</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic17.php">第17回　包丁の使い方・動かし方</a></p>
	<p style="margin-bottom: 0">≫ <a href="recipe-technic16.php">第16回　玉ねぎのみじん切りの方法</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic15.php">第15回　乱切り・くし形切りの方法</a></p>
	<p style="margin-bottom: 0">≫ <a href="recipe-technic14.php">第14回　あさりの砂抜き・塩抜き方法</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic13.php">第13回　千切りの方法</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic12.php">第12回　計量の仕方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic11.php">第11回　輪切り・半月切り・いちょう切りの方法</a></p>
	<p style="margin-bottom: 0">≫ <a href="recipe-technic10.php">第10回　ゆで卵の作り方</a></p>
	<p style="margin-bottom: 0">≫ <a href="recipe-technic09.php">第9回　揚げ物の基本</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic08.php">第8回　卵の割り方、卵黄と卵白の分け方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic07.php">第7回　にぼしだしの取り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic06.php">第6回　かつお昆布だしの取り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic05.php">第5回　昆布だしの取り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic04.php">第4回　アクの取り方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic03.php">第3回　野菜の皮のむき方</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic02.php">第2回　弱火・中火・強火って何度？火加減の正しい調整方法とは</a></p>
  <p style="margin-bottom: 0">≫ <a href="recipe-technic01.php">第1回　料理のプロに教わる！包丁の正しい持ち方・姿勢</a></p>
</div>
